/* The following code was generated by JFlex 1.6.0 */

import java_cup.runtime.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>Lexer.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\2\1\2\0\1\1\22\0\1\23\7\0\1\5\1\7\1\6"+
    "\1\25\1\40\1\31\1\22\1\32\12\2\1\0\1\44\1\34\1\33"+
    "\1\35\2\0\1\42\3\4\1\24\25\4\4\0\1\41\1\0\1\15"+
    "\1\3\1\37\1\26\1\13\1\14\1\30\1\36\1\27\2\3\1\16"+
    "\1\3\1\20\1\21\2\3\1\11\1\17\1\10\1\12\3\3\1\43"+
    "\1\3\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff95\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\6\4\1\7\1\10\1\4\1\11\1\1\1\12\1\13"+
    "\1\14\1\15\1\16\1\1\1\17\1\0\1\20\1\0"+
    "\1\21\10\4\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\4\0\2\4\1\33\1\4\1\34"+
    "\1\4\1\35\1\36\3\0\1\37\1\40\1\41\1\4"+
    "\2\0\1\2\1\42\3\0\1\20\5\0\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\157\0\224\0\271\0\336\0\45"+
    "\0\u0103\0\u0128\0\u014d\0\u0172\0\u0197\0\u01bc\0\45\0\u01e1"+
    "\0\u0206\0\u022b\0\u0250\0\45\0\u0275\0\u029a\0\45\0\45"+
    "\0\u02bf\0\45\0\u02e4\0\u0309\0\u032e\0\45\0\u0353\0\u0378"+
    "\0\u039d\0\u03c2\0\u03e7\0\u040c\0\u0431\0\u0456\0\45\0\224"+
    "\0\224\0\45\0\45\0\45\0\45\0\45\0\45\0\u047b"+
    "\0\u04a0\0\u04c5\0\u04ea\0\u050f\0\u0534\0\224\0\u0559\0\224"+
    "\0\u057e\0\224\0\224\0\u05a3\0\u05c8\0\u05ed\0\224\0\224"+
    "\0\224\0\u0612\0\u0637\0\u065c\0\45\0\224\0\u0681\0\u06a6"+
    "\0\u06cb\0\u06a6\0\u06f0\0\u0715\0\u073a\0\u075f\0\u0784\0\45";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\1\7\1\10"+
    "\1\11\1\12\1\5\1\13\1\14\1\5\1\15\1\5"+
    "\1\16\1\5\1\17\1\3\1\2\1\20\1\5\1\21"+
    "\1\5\1\22\1\23\1\24\1\25\1\26\2\5\1\27"+
    "\1\30\1\31\1\5\1\32\46\0\1\3\21\0\1\3"+
    "\23\0\1\4\10\0\1\33\6\0\1\34\2\33\22\0"+
    "\3\5\3\0\12\5\2\0\1\5\1\0\3\5\5\0"+
    "\2\5\1\0\3\5\7\0\1\35\60\0\1\36\24\0"+
    "\3\5\3\0\1\5\1\37\10\5\2\0\1\5\1\0"+
    "\3\5\5\0\1\40\1\5\1\0\3\5\3\0\3\5"+
    "\3\0\3\5\1\41\6\5\2\0\1\5\1\0\3\5"+
    "\5\0\2\5\1\0\3\5\3\0\3\5\3\0\6\5"+
    "\1\42\2\5\1\43\2\0\1\5\1\0\3\5\5\0"+
    "\2\5\1\0\3\5\3\0\3\5\3\0\5\5\1\44"+
    "\4\5\2\0\1\5\1\0\3\5\5\0\2\5\1\0"+
    "\3\5\3\0\3\5\3\0\3\5\1\45\6\5\2\0"+
    "\1\5\1\0\3\5\5\0\2\5\1\0\3\5\3\0"+
    "\3\5\3\0\11\5\1\46\2\0\1\5\1\0\3\5"+
    "\5\0\2\5\1\0\3\5\23\0\1\47\24\0\3\5"+
    "\3\0\4\5\1\50\3\5\1\51\1\5\2\0\1\5"+
    "\1\0\3\5\5\0\2\5\1\0\3\5\23\0\1\52"+
    "\44\0\1\53\53\0\1\54\1\0\1\55\1\0\1\56"+
    "\42\0\1\57\22\0\1\60\56\0\1\61\1\0\1\61"+
    "\1\62\2\0\1\61\15\0\1\34\10\0\1\33\7\0"+
    "\2\33\20\0\6\63\1\0\36\63\2\0\3\5\3\0"+
    "\2\5\1\64\7\5\2\0\1\5\1\0\3\5\5\0"+
    "\2\5\1\0\3\5\3\0\3\5\3\0\3\5\1\65"+
    "\6\5\2\0\1\5\1\0\3\5\5\0\2\5\1\0"+
    "\3\5\3\0\3\5\3\0\12\5\2\0\1\5\1\0"+
    "\3\5\5\0\1\5\1\66\1\0\3\5\3\0\3\5"+
    "\3\0\7\5\1\67\2\5\2\0\1\5\1\0\3\5"+
    "\5\0\2\5\1\0\3\5\3\0\3\5\3\0\4\5"+
    "\1\70\5\5\2\0\1\5\1\0\3\5\5\0\2\5"+
    "\1\0\3\5\3\0\3\5\3\0\6\5\1\71\3\5"+
    "\2\0\1\5\1\0\3\5\5\0\2\5\1\0\3\5"+
    "\3\0\3\5\3\0\1\72\11\5\2\0\1\5\1\0"+
    "\3\5\5\0\2\5\1\0\3\5\3\0\3\5\3\0"+
    "\1\73\11\5\2\0\1\5\1\0\3\5\5\0\2\5"+
    "\1\0\3\5\12\0\1\74\61\0\1\62\45\0\1\75"+
    "\15\0\6\63\1\76\36\63\2\0\3\5\3\0\3\5"+
    "\1\77\6\5\2\0\1\5\1\0\3\5\5\0\2\5"+
    "\1\0\3\5\3\0\3\5\3\0\10\5\1\100\1\5"+
    "\2\0\1\5\1\0\3\5\5\0\2\5\1\0\3\5"+
    "\3\0\3\5\3\0\3\5\1\101\6\5\2\0\1\5"+
    "\1\0\3\5\5\0\2\5\1\0\3\5\3\0\3\5"+
    "\3\0\7\5\1\102\2\5\2\0\1\5\1\0\3\5"+
    "\5\0\2\5\1\0\3\5\16\0\1\103\57\0\1\104"+
    "\14\0\6\63\1\76\1\105\35\63\2\0\3\5\3\0"+
    "\3\5\1\106\6\5\2\0\1\5\1\0\3\5\5\0"+
    "\2\5\1\0\3\5\44\0\1\107\30\0\1\110\37\0"+
    "\1\111\32\0\1\112\73\0\1\113\16\0\1\114\46\0"+
    "\1\115\46\0\1\116\37\0\1\117\47\0\1\120\31\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1961];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\6\1\1\11\4\1\1\11"+
    "\2\1\2\11\1\1\1\11\1\0\1\1\1\0\1\11"+
    "\10\1\1\11\2\1\6\11\4\0\10\1\3\0\4\1"+
    "\2\0\1\11\1\1\3\0\1\1\5\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[80];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    /* To create a new java_cup.runtime.Symbol with information about
       the current token, the token will have no value in this
       case. */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Also creates a new java_cup.runtime.Symbol with information
       about the current token, but this object has a value. */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 136) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { throw new Error("Illegal character <"+yytext()+">");
          }
        case 36: break;
        case 2: 
          { 
          }
        case 37: break;
        case 3: 
          { return symbol(sym.INT, new Integer(yytext()));
          }
        case 38: break;
        case 4: 
          { return symbol(sym.IDENT, new Id(yytext()));
          }
        case 39: break;
        case 5: 
          { return symbol(sym.LPAREN);
          }
        case 40: break;
        case 6: 
          { return symbol(sym.RPAREN);
          }
        case 41: break;
        case 7: 
          { return symbol(sym.DOT);
          }
        case 42: break;
        case 8: 
          { return symbol(sym.PLUS);
          }
        case 43: break;
        case 9: 
          { return symbol(sym.MINUS);
          }
        case 44: break;
        case 10: 
          { return symbol(sym.EQUAL);
          }
        case 45: break;
        case 11: 
          { return symbol(sym.LESS);
          }
        case 46: break;
        case 12: 
          { return symbol(sym.GREATER);
          }
        case 47: break;
        case 13: 
          { return symbol(sym.COMMA);
          }
        case 48: break;
        case 14: 
          { return symbol(sym.IDENT, Id.gen());
          }
        case 49: break;
        case 15: 
          { return symbol(sym.SEMICOLON);
          }
        case 50: break;
        case 16: 
          { return symbol(sym.FLOAT, new java.lang.Float(yytext()));
          }
        case 51: break;
        case 17: 
          { return symbol(sym.AST_DOT);
          }
        case 52: break;
        case 18: 
          { return symbol(sym.PLUS_DOT);
          }
        case 53: break;
        case 19: 
          { return symbol(sym.IF);
          }
        case 54: break;
        case 20: 
          { return symbol(sym.IN);
          }
        case 55: break;
        case 21: 
          { return symbol(sym.MINUS_DOT);
          }
        case 56: break;
        case 22: 
          { return symbol(sym.SLASH_DOT);
          }
        case 57: break;
        case 23: 
          { return symbol(sym.LESS_MINUS);
          }
        case 58: break;
        case 24: 
          { return symbol(sym.LESS_EQUAL);
          }
        case 59: break;
        case 25: 
          { return symbol(sym.LESS_GREATER);
          }
        case 60: break;
        case 26: 
          { return symbol(sym.GREATER_EQUAL);
          }
        case 61: break;
        case 27: 
          { return symbol(sym.REC);
          }
        case 62: break;
        case 28: 
          { return symbol(sym.EOF);
          }
        case 63: break;
        case 29: 
          { return symbol(sym.LET);
          }
        case 64: break;
        case 30: 
          { return symbol(sym.NOT);
          }
        case 65: break;
        case 31: 
          { return symbol(sym.BOOL, true);
          }
        case 66: break;
        case 32: 
          { return symbol(sym.THEN);
          }
        case 67: break;
        case 33: 
          { return symbol(sym.ELSE);
          }
        case 68: break;
        case 34: 
          { return symbol(sym.BOOL, false);
          }
        case 69: break;
        case 35: 
          { return symbol(sym.ARRAY_CREATE);
          }
        case 70: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
